### ISSUE TITLE
[QUESTION] Do your stubs support `qgis.PyQt`?

### ISSUE THREAD

**Issue by MrChebur** [leonhard-s/qgis-stubs#5]
Installing these stubs helped me a lot, but still there are some problems in lines of code:
```
from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
```
Сode execution goes without any problems.
The question is, do your stubs support `qgis.PyQt`?

![pycharm64_EoyFw37AjN](https://user-images.githubusercontent.com/20655102/235657724-30a1fae6-2a39-4faa-8d8d-13dabf101267.png)

**Comment by leonhard-s** [comment]
Hi, the `qgis.PyQt` namespace is a runtime alias for `PyQt5` to decouple scripts from the version of Qt used by QGIS.

I originally attempted to have the QGIS stubs forward this symbol to the appropriate PyQt version, but neither MyPy nor Pylance handled this correctly. These kinds of aliases do work for regular Python modules, but the PyQt stubs are also provided by a stub package (`PyQt5-stubs` in this case), which likely caused issues with the type checkers.

For my plugins, I settled on simply importing from `PyQt5` directly (e.g. `from PyQt5 import QtGui`), which is handled correctly by the type checkers and also works for runtime as `qgis.PyQt` points to the same object. But this does of course require extra consideration once QGIS moves to Qt6.

I will have a look to see if the issues with aliasing a stub module have been resolved in Pylance and Mypy.

**Comment by leonhard-s** [comment]
It is possible to make the syntax your first snippet uses work by reimporting the symbols into the stubs's own modules:
```py
# qgis-stubs/__init__.pyi ###############################################
from . import _3d, analysis, core, gui, processing, PyQt, server


# qgis-stubs/PyQt.pyi ###################################################
from PyQt5 import (Qt3DAnimation, Qt3DCore, ... , QtXml, QtXmlPatterns)

__all__ = [
    'Qt3DAnimation',
    'Qt3DCore',
    ... ,
    'QtXml',
    'QtXmlPatterns'
]
```

However, a deep relative import into the PyQt module itself would still be an error.  `from qgis.PyQt import QtCore` works because `QtCore` is a symbol in the file `qgis/PyQt.pyi`. `from qgis.PyQt.QtCore import pyqtSignal` would try to import from an object instead.  
Of course, we could keep going with this pattern and re-export every symbol from every submodule of PyQt5, but at that point we may as well just include the `PyQt5-stubs` source code (which should work given both projects are GPL3).


I am unsure whether either form of replicating/including the Qt names within `qgis.PyQt` is warranted. For small projects, updating the imports every ~10 years when a new QGIS version arrives is trivial, and even in larger projects the search-and-replace overhead is probably outweighed by needing to track down the API changes that occurred since the last major Qt version.

I am open to feedback on this though, as I said it is not impossible to eliminate PyQt5 as a dependency and just redistribute its source code instead.

**Comment by MrChebur** [comment]
Thank you for such a detailed explanation. 
As a summary: at the moment `qgis-stubs` does not support `qgis.PyQt`.
Feel free to close this issue.
